# Generated by Django 5.0.6 on 2024-09-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='course',
            field=models.CharField(default=None, max_length=70),
        ),
    ]
