# Generated by Django 5.0.6 on 2024-09-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_tasks_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
