# Generated by Django 5.0.6 on 2024-09-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('course', models.CharField(default=None, max_length=70)),
                ('due_on', models.DateField()),
                ('accomplished', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/tasks')),
                ('graded', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.students')),
            ],
        ),
    ]
