# Generated by Django 5.0.6 on 2024-09-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='temporary_field',
            field=models.CharField(default='temp', max_length=50),
        ),
    ]
