# Generated by Django 5.0.6 on 2024-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_remove_tasks_temporary_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
