# Generated by Django 5.0.6 on 2024-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_tasks_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_on',
            field=models.DateField(default=None),
        ),
    ]
