# Generated by Django 5.0.6 on 2024-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_alter_tasks_due_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
