# Generated by Django 5.0.6 on 2024-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_alter_tasks_due_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
