# Generated by Django 5.0.6 on 2024-09-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_schedule_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
    ]
