# Generated by Django 5.0.6 on 2024-09-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_remove_schedule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=2, max_length=5),
        ),
    ]
