# Generated by Django 5.0.6 on 2024-09-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_schedule_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=2),
        ),
    ]
