# Generated by Django 5.0.6 on 2024-09-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0015_alter_schedule_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='subject',
            field=models.CharField(default=None, max_length=75),
        ),
    ]
