# Generated by Django 5.0.6 on 2024-09-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0016_teachers_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
