# Generated by Django 5.0.6 on 2024-09-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_alter_teachers_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
