# Generated by Django 5.0.6 on 2024-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_alter_teachers_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_link', models.CharField(max_length=300, null=True)),
                ('video_url', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
