# Generated by Django 5.0.6 on 2024-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='video_url',
        ),
        migrations.AddField(
            model_name='resources',
            name='link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='link_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
