# Generated by Django 5.0.6 on 2024-09-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0020_remove_resources_file_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='course',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.students')),
            ],
        ),
    ]
