# Generated by Django 5.0.6 on 2024-09-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0021_resources_course_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user',
            new_name='std_user',
        ),
        migrations.AddField(
            model_name='messages',
            name='teach_user',
            field=models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.teachers'),
        ),
    ]
